<?php
return array( 
	"SITE_URL" 				=> "http://labhshubh.com/housesharemarket/",
	"SITE_TITLE" 			=> "Housesharemarket",
	"SITE_EMAIL" 			=> "admin@gmail.com",
	"NEED_ANY_HELP_EMAIL"	=> "info@housesharemarket.com",
	"NEED_ANY_HELP_PHONE"	=> "124567890",
	"USER_ROLES" 			=> array(1=>'Admin', 2=>'User'),
	"PAGINATION" 			=> 20,
	"FRONT_PAGINATION" 		=> 10,
	"GENDER" 				=> array(1=>'Male',  2=>'Female'),
	"STATUS" 				=> array('1'=>'Active', '0'=>'Inactive'),
	"YES_NO" 				=> array('1'=>'Yes', '2'=>'No'),
	"USER_THUMB_WIDTH"		=> 150,
	"ADS_THUMB_WIDTH"		=> 150,
	"PROPERTY_TYPE" 		=> array('1'=>'Flat/Apartment', '2'=>'House', '3'=>'Property'),
	"LIVING_ROOM" 		    => array('1'=>'Yes, there is a shared living room', '2'=>'No'),
	"MINIMUM_STAY" 		    => array('1'=>'1 Month', '2'=>'2 Months', '3'=>'3 Months', '4'=>'4 Months', '5'=>'5 Months', '6'=>'6 Months', '7'=>'7 Months', '8'=>'8 Months', '9'=>'9 Months', '10'=>'10 Months', '11'=>'11 Months', '12'=>'1 Year', '13'=>'1 Year 3 Months', '14'=>'1 Year 6 Months', '15'=>'1 Year 9 Months', '16'=>'2 Years', '17'=>'3 Years'),
	"MAXIMUM_STAY" 		    => array('1'=>'1 Month', '2'=>'2 Months', '3'=>'3 Months', '4'=>'4 Months', '5'=>'5 Months', '6'=>'6 Months', '7'=>'7 Months', '8'=>'8 Months', '9'=>'9 Months', '10'=>'10 Months', '11'=>'11 Months', '12'=>'1 Year', '13'=>'1 Year 3 Months', '14'=>'1 Year 6 Months', '15'=>'1 Year 9 Months', '16'=>'2 Years', '17'=>'3 Years'),
	"DAYS_AVAILABLE" 		=> array('1'=>'7 days a week', '2'=>'Mon to Fri only', '3'=>'Weekends only'),
	"REFERENCES_REQUIRED" 	=> array('1'=>'Yes', '2'=>'No'),
	"BILLS_INCLUDED" 		=> array('1'=>'Yes', '2'=>'No', '3'=>'Some'),
	"OCCUPATION_TYPE" 	    => array('1'=>'Student', '2'=>'Professional'),
	"MISC_TYPE" 	        => array('1'=>'DSS welcome', '2'=>'Vegetarians preferred'),
	"AVAILABLE_TYPE" 	    => array('1'=>'Available', '2'=>'Taken'),
	"ROOM_COST_TYPE" 	    => array('1'=>'per week', '2'=>'per calendar month'),
	"ROOM_SIZE_TYPE" 	    => array('1'=>'Single', '2'=>'Double'),
	"API_KEY_GOOGLE"		=> 'AIzaSyAIJfFJF_ejFgK2eY-ycm6hZC8zkYYOq-0',
	
	"ADVERTISE_TYPE" 		=> array('rooms-to-rent'=>'Rooms to Rent', 'whole-property-to-let'=>'Whole Property to Let', 'room-wanted'=>'Room Wanted'),
	"ADVERTISE_TYPE_TYPE" 	=> array('1'=>'Rooms to Rent', '2'=>'Whole Property to Let', '3'=>'Room Wanted'),
	"ADVERTISE_TYPE_NUMBER" => array('rooms-to-rent'=>'1', 'whole-property-to-let'=>'2', 'room-wanted'=>'3'),
	"ADVERTISE_TYPE_SEARCH" => array('1'=>'Rooms for Rent', '2'=>'Rooms Wanted', '3'=>'Buddy ups'),
	
	"FURNISHED_TYPE"        => array('1'=>'Furnished', '2'=>'Part furnished', '3'=>'Unfurnished'),
	"I_AM_WE_ARE"           => array('1'=>'1 male', '2'=>'1 female', '3'=>'1 male 1 female', '4'=>'2 males', '5'=>'2 females'),
	"LOOKING_FOR"           => array('1'=>'a single or double room', '2'=>'a double room', '3'=>'a double room (we are partners)', '4'=>'a twin room or 2 rooms', '5'=>'2 rooms'),
	"SEXUAL_ORIENTATION"    => array('1'=>'Undisclosed', '2'=>'Straight', '3'=>'Gay/Lesbian', '4'=>'Bi-sexual'),
);  